name: Close Linked Issues on PR Closure

on: 
  pull_request:
    types: [closed]

jobs:
  close_linked_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: peter-evans/close-issue@v2
        with: 
          issue-type: linked
